/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LeakCmp {
    }
    interface PlainCmp {
    }
}
declare global {
    interface HTMLLeakCmpElement extends Components.LeakCmp, HTMLStencilElement {
    }
    var HTMLLeakCmpElement: {
        prototype: HTMLLeakCmpElement;
        new (): HTMLLeakCmpElement;
    };
    interface HTMLPlainCmpElement extends Components.PlainCmp, HTMLStencilElement {
    }
    var HTMLPlainCmpElement: {
        prototype: HTMLPlainCmpElement;
        new (): HTMLPlainCmpElement;
    };
    interface HTMLElementTagNameMap {
        "leak-cmp": HTMLLeakCmpElement;
        "plain-cmp": HTMLPlainCmpElement;
    }
}
declare namespace LocalJSX {
    interface LeakCmp {
    }
    interface PlainCmp {
    }
    interface IntrinsicElements {
        "leak-cmp": LeakCmp;
        "plain-cmp": PlainCmp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "leak-cmp": LocalJSX.IntrinsicElements["leak-cmp"] & JSXBase.HTMLAttributes<HTMLLeakCmpElement>;
            "plain-cmp": LocalJSX.IntrinsicElements["plain-cmp"] & JSXBase.HTMLAttributes<HTMLPlainCmpElement>;
        }
    }
}
